let lessons = [
  {
    id: 1001,
    subject: "Math",
    location: "London",
    price: 150,
    space: 3,
    image: "./images/math1.jpg",
    rating: 2,
  },
  {
    id: 1002,
    subject: "Biology",
    location: "Manchester",
    price: 160,
    space: 4,
    image: "./images/math1.jpg",
    rating: 1,
  },
  {
    id: 1003,
    subject: "Chemistry",
    location: "Birmingham",
    price: 170,
    space: 9,
    image: "./images/chemistry.jpg",
    rating: 2,
  },
  {
    id: 1004,
    subject: "Religious Studies",
    location: "Leicester",
    price: 180,
    space: 5,
    image: "./images/history.jpg",
    rating: 3,
  },
  {
    id: 1005,
    subject: "History",
    location: "Liverpool",
    price: 190,
    space: 1,
    image: "./images/history.jpg",
    rating: 6,
  },
  {
    id: 1006,
    subject: "Language",
    location: "Coventry",
    price: 200,
    space: 2,
    image: "./images/language.jpg",
    rating: 5,
  },
  {
    id: 1007,
    subject: "Literature",
    location: "Wales",
    price: 210,
    space: 10,
    image: "./images/literature.jpg",
    rating: 9,
  },
  {
    id: 1008,
    subject: "Physics",
    location: "Stoke",
    price: 220,
    space: 7,
    image: "./images/physics.jpg",
    rating: 8,
  },
  {
    id: 1009,
    subject: "Science",
    location: "London",
    price: 230,
    space: 7,
    image: "./images/ss.jpg",
    rating: 7,
  },
  {
    id: 1010,
    subject: "Social Studies",
    location: "Chichester",
    price: 240,
    space: 10,
    image: "./images/ss.jpg",
  },
];
